name: llm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - comm=0.2.1
  - debugpy=1.6.7
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - ipykernel=6.28.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.14
  - packaging=24.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pip=24.0
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.10.14
  - python-dateutil=2.9.0post0
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - accelerate==0.33.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.3.4
      - aiohttp==3.10.1
      - aiosignal==1.3.1
      - altair==5.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - appdirs==1.4.4
      - asgiref==3.8.1
      - async-timeout==4.0.3
      - attrs==24.1.0
      - backcall==0.2.0
      - backoff==2.2.1
      - bcrypt==4.2.0
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.43.3
      - bleach==6.1.0
      - blinker==1.8.2
      - blis==0.7.11
      - braceexpand==0.1.7
      - build==1.2.1
      - cachetools==5.4.0
      - catalogue==2.0.10
      - certifi==2024.7.4
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - chroma-hnswlib==0.7.6
      - chromadb==0.5.5
      - chromedriver-autoinstaller==0.6.4
      - click==8.1.7
      - cloudpathlib==0.18.1
      - coloredlogs==15.0.1
      - confection==0.1.5
      - contexttimer==0.3.3
      - contourpy==1.2.1
      - cssselect==1.2.0
      - cycler==0.12.1
      - cymem==2.0.8
      - dataclasses-json==0.6.7
      - datasets==2.20.0
      - decorator==4.4.2
      - decord==0.6.0
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - dill==0.3.8
      - dirtyjson==1.0.8
      - distlib==0.3.8
      - distro==1.9.0
      - docopt==0.6.2
      - docstring-parser==0.16
      - einops==0.8.0
      - evaluate==0.4.2
      - fairscale==0.4.4
      - faiss-cpu==1.8.0.post1
      - fastapi==0.112.0
      - fastembed-gpu==0.3.4
      - fastjsonschema==2.20.0
      - feedfinder2==0.0.4
      - feedparser==6.0.11
      - ffmpy==0.4.0
      - filelock==3.13.1
      - fire==0.6.0
      - flash-attn==2.6.3
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - ftfy==6.2.3
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.32.0
      - google-search-results==2.4.2
      - googleapis-common-protos==1.63.2
      - gradio==4.41.0
      - gradio-client==1.3.0
      - greenlet==3.0.3
      - grpcio==1.65.4
      - grpcio-tools==1.65.4
      - h11==0.14.0
      - h2==4.1.0
      - hpack==4.0.0
      - html2text==2024.2.26
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.5
      - humanfriendly==10.0
      - hyperframe==6.0.1
      - identify==2.6.0
      - idna==3.7
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.0.0
      - importlib-resources==6.4.0
      - iopath==0.1.10
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - jieba3k==0.35.1
      - jinja2==3.1.3
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.13
      - kaggle==1.6.17
      - kiwisolver==1.4.5
      - kubernetes==30.1.0
      - langchain==0.2.12
      - langchain-community==0.2.11
      - langchain-core==0.2.28
      - langchain-huggingface==0.0.3
      - langchain-openai==0.1.20
      - langchain-text-splitters==0.2.2
      - langcodes==3.4.0
      - langsmith==0.1.98
      - language-data==1.2.0
      - lark==1.1.9
      - lazy-loader==0.4
      - llama-cloud==0.0.11
      - llama-index==0.10.61
      - llama-index-agent-openai==0.2.9
      - llama-index-cli==0.1.13
      - llama-index-core==0.10.61
      - llama-index-embeddings-huggingface==0.2.2
      - llama-index-embeddings-openai==0.1.11
      - llama-index-indices-managed-llama-cloud==0.2.7
      - llama-index-legacy==0.9.48
      - llama-index-llms-huggingface==0.2.5
      - llama-index-llms-openai==0.1.27
      - llama-index-multi-modal-llms-openai==0.1.8
      - llama-index-program-openai==0.1.7
      - llama-index-question-gen-openai==0.1.3
      - llama-index-readers-file==0.1.32
      - llama-index-readers-llama-parse==0.1.6
      - llama-index-readers-web==0.1.23
      - llama-index-retrievers-videodb==0.1.1
      - llama-index-vector-stores-chroma==0.1.10
      - llama-index-vector-stores-qdrant==0.2.14
      - llama-parse==0.4.9
      - loguru==0.7.2
      - lxml==5.2.2
      - marisa-trie==1.2.0
      - markdown-it-py==3.0.0
      - markdownify==0.13.1
      - markupsafe==2.1.5
      - marshmallow==3.21.3
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - minijinja==2.0.1
      - mistune==3.0.2
      - mmh3==4.1.0
      - monotonic==1.6
      - moviepy==1.0.3
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - murmurhash==1.0.10
      - mypy-extensions==1.0.0
      - narwhals==1.4.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - networkx==3.2.1
      - newspaper3k==0.2.8
      - nltk==3.8.1
      - nodeenv==1.9.1
      - numpy==1.26.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnxruntime==1.18.1
      - onnxruntime-gpu==1.18.1
      - openai==1.39.0
      - openai-clip==1.0.1
      - opencv-python-headless==4.5.5.64
      - opendatasets==0.1.22
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.11.1
      - opentelemetry-instrumentation==0.47b0
      - opentelemetry-instrumentation-asgi==0.47b0
      - opentelemetry-instrumentation-fastapi==0.47b0
      - opentelemetry-proto==1.11.1
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-util-http==0.47b0
      - orjson==3.10.6
      - outcome==1.3.0.post0
      - overrides==7.7.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - peft==0.12.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pipreqs==0.5.0
      - playwright==1.45.1
      - plotly==5.23.0
      - portalocker==2.10.1
      - posthog==3.5.0
      - pre-commit==3.8.0
      - preshed==3.0.9
      - proglog==0.1.10
      - protobuf==3.20.3
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.8
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydeck==0.9.1
      - pydub==0.25.1
      - pyee==11.1.0
      - pyparsing==3.1.2
      - pypdf==4.3.1
      - pypika==0.48.9
      - pyproject-hooks==1.1.0
      - pysbd==0.3.4
      - pysocks==1.7.1
      - pystemmer==2.2.0.1
      - python-dotenv==1.0.1
      - python-magic==0.4.27
      - python-multipart==0.0.9
      - python-slugify==8.0.4
      - pytube==15.0.0
      - pytubefix==6.12.0
      - pytz==2024.1
      - pyyaml==6.0.1
      - qdrant-client==1.10.1
      - ragas==0.1.14
      - referencing==0.35.1
      - regex==2024.7.24
      - requests==2.32.3
      - requests-file==2.1.0
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rpds-py==0.20.0
      - rsa==4.9
      - ruff==0.5.6
      - safetensors==0.4.4
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - selenium==4.23.1
      - semantic-version==2.10.0
      - sentence-transformers==3.0.1
      - sentencepiece==0.2.0
      - sgmllib3k==1.0.0
      - shellingham==1.5.4
      - shtab==1.7.1
      - smart-open==7.0.4
      - smmap==5.0.1
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - spider-client==0.0.27
      - sqlalchemy==2.0.32
      - srsly==2.4.8
      - starlette==0.37.2
      - streamlit==1.37.1
      - striprtf==0.0.26
      - sympy==1.12
      - tenacity==8.5.0
      - termcolor==2.4.0
      - text-generation==0.7.0
      - text-unidecode==1.3
      - thinc==8.2.5
      - threadpoolctl==3.5.0
      - tifffile==2024.8.10
      - tiktoken==0.7.0
      - timm==0.4.12
      - tinycss2==1.3.0
      - tinysegmenter==0.3
      - tldextract==5.1.2
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.0.1
      - tomlkit==0.12.0
      - torch==2.3.0+cu118
      - torchaudio==2.3.0+cu118
      - torchvision==0.18.0+cu118
      - tqdm==4.66.5
      - transformers==4.44.0
      - trio==0.26.1
      - trio-websocket==0.11.1
      - triton==2.3.0
      - trl==0.9.6
      - typer==0.12.3
      - typing-inspect==0.9.0
      - tyro==0.8.5
      - tzdata==2024.1
      - urllib3==2.2.2
      - uvicorn==0.30.5
      - uvloop==0.19.0
      - videodb==0.2.4
      - virtualenv==20.26.3
      - wasabi==1.1.3
      - watchdog==4.0.2
      - watchfiles==0.22.0
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webdataset==0.2.96
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==12.0
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - wsproto==1.2.0
      - xformers==0.0.26.post1+cu118
      - xxhash==3.4.1
      - yarg==0.1.9
      - yarl==1.9.4
      - youtube-dl==2021.12.17
      - zipp==3.19.2
